package com.model;

/**
 * TOrderItem generated by MyEclipse Persistence Tools
 */

public class TOrderItem implements java.io.Serializable
{

	// Fields

	private Integer orderItemId;

	private Integer orderId;

	private Integer goodsId;

	private Integer goodsQuantity;
	
	private TGoods goods;//表里没有。自己加的
	
	private TUser user;
	
	private TOrder order;

	// Constructors

	/** default constructor */
	public TOrderItem()
	{
	}

	/** full constructor */
	public TOrderItem(Integer orderId, Integer goodsId, Integer goodsQuantity)
	{
		this.orderId = orderId;
		this.goodsId = goodsId;
		this.goodsQuantity = goodsQuantity;
	}

	// Property accessors

	public Integer getOrderItemId()
	{
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId)
	{
		this.orderItemId = orderItemId;
	}

	public Integer getOrderId()
	{
		return this.orderId;
	}

	public void setOrderId(Integer orderId)
	{
		this.orderId = orderId;
	}

	public Integer getGoodsId()
	{
		return this.goodsId;
	}

	public TGoods getGoods()
	{
		return goods;
	}

	public void setGoods(TGoods goods)
	{
		this.goods = goods;
	}

	public void setGoodsId(Integer goodsId)
	{
		this.goodsId = goodsId;
	}

	public Integer getGoodsQuantity()
	{
		return this.goodsQuantity;
	}

	public void setGoodsQuantity(Integer goodsQuantity)
	{
		this.goodsQuantity = goodsQuantity;
	}

	public TUser getUser() {
		return user;
	}

	public void setUser(TUser user) {
		this.user = user;
	}

	public TOrder getOrder() {
		return order;
	}

	public void setOrder(TOrder order) {
		this.order = order;
	}
	
}