package com.model;

/**
 * TOrder generated by MyEclipse Persistence Tools
 */

public class TOrder implements java.io.Serializable
{

	// Fields

	private Integer orderId;

	private String orderBianhao;

	private String orderDate;

	private String orderZhuangtai;
	
	private String odderSonghuodizhi;

	private String odderFukuangfangshi;
	
	private String store;

	private Integer orderUserId;
	
	private int orderJine=0;
	private int sjfk=0;
	private int shid;
	private String shname;
	private int pid;
	private TUser user;
	
	
	
	// Constructors

	public TUser getUser() {
		return user;
	}

	public void setUser(TUser user) {
		this.user = user;
	}

	/** default constructor */
	public TOrder()
	{
	}

	/** full constructor */
	public TOrder(String orderBianhao, String orderDate, String orderZhuangtai,
			Integer orderUserId)
	{
		this.orderBianhao = orderBianhao;
		this.orderDate = orderDate;
		this.orderZhuangtai = orderZhuangtai;
		this.orderUserId = orderUserId;
	}

	
 
	public String getStore() {
		return store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Integer getOrderId()
	{
		return this.orderId;
	}

	public void setOrderId(Integer orderId)
	{
		this.orderId = orderId;
	}

	public String getOrderBianhao()
	{
		return this.orderBianhao;
	}

	public int getOrderJine()
	{
		return orderJine;
	}

	public void setOrderJine(int orderJine)
	{
		this.orderJine = orderJine;
	}
	

	public String getOdderFukuangfangshi()
	{
		return odderFukuangfangshi;
	}

	public void setOdderFukuangfangshi(String odderFukuangfangshi)
	{
		this.odderFukuangfangshi = odderFukuangfangshi;
	}

	public String getOdderSonghuodizhi()
	{
		return odderSonghuodizhi;
	}

	public void setOdderSonghuodizhi(String odderSonghuodizhi)
	{
		this.odderSonghuodizhi = odderSonghuodizhi;
	}

	public void setOrderBianhao(String orderBianhao)
	{
		this.orderBianhao = orderBianhao;
	}

	public String getOrderDate()
	{
		return this.orderDate;
	}

	public void setOrderDate(String orderDate)
	{
		this.orderDate = orderDate;
	}

	public String getOrderZhuangtai()
	{
		return this.orderZhuangtai;
	}

	public void setOrderZhuangtai(String orderZhuangtai)
	{
		this.orderZhuangtai = orderZhuangtai;
	}

	public Integer getOrderUserId()
	{
		return this.orderUserId;
	}

	public void setOrderUserId(Integer orderUserId)
	{
		this.orderUserId = orderUserId;
	}

	public int getSjfk() {
		return sjfk;
	}

	public void setSjfk(int sjfk) {
		this.sjfk = sjfk;
	}

	public int getShid() {
		return shid;
	}

	public void setShid(int shid) {
		this.shid = shid;
	}

	public String getShname() {
		return shname;
	}

	public void setShname(String shname) {
		this.shname = shname;
	}

	public int getPid() {
		return pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}
	

}